In [7]:
import pandas as pd

In [8]:
df = pd.read_parquet("./data/mta_transfer.parquet")
df.head()

                                                                             address  \
block_number transaction_index log_index
10450640     159               153        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10450649     222               173        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
                               176        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10476280     131               164        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10476285     187               123        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2

                                                                                 block_hash  \
block_number transaction_index log_index
10450640     159               153        0x3e8959e9f1b28b7a7e597379bdefa00f8be1f62f2125...
10450649     222               173        0x7b462b18f27f23c3c44af55f88b04eb5bb1f6dd6da25...
                               176        0x7b462b18f27f23c3c44af55f88b04eb5bb1f6dd6da25...
10476280     131               164        0xb5a0e752fd84e60aaa8d3f72a12f8c0b5bcb6dad7f84...
10476285     187               123        0x1a58ecaefe536ba4cf2718879f05de9ed01f621d1525...

                                                                           transaction_hash  \
block_number transaction_index log_index
10450640     159               153        0x998c0f49c32ecf1bb76378c6ecc92a9ea52ab9a161a3...
10450649     222               173        0xb5cc04a1eeca79ab540357804b3c76eee7d61a38bb24...
                               176        0xb5cc04a1eeca79ab540357804b3c76eee7d61a38bb24...
10476280     131               164        0x662b71919cc53c617d2d5c600240e6bafcf49beec5b4...
10476285     187               123        0xd8b4a056f73a7f43eb7faeb31231579bcd02dcee5c5f...

                                                                    contract_address  \
block_number transaction_index log_index
10450640     159               153        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10450649     222               173        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
                               176        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10476280     131               164        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2
10476285     187               123        0xa3bed4e1c75d00fa6f4e5e6922db7261b5e9acd2

                                         event_name  \
block_number transaction_index log_index
10450640     159               153         Transfer
10450649     222               173         Transfer
                               176         Transfer
10476280     131               164         Transfer
10476285     187               123         Transfer

                                                                                 event_hash  \
block_number transaction_index log_index
10450640     159               153        0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...
10450649     222               173        0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...
                               176        0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...
10476280     131               164        0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...
10476285     187               123        0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4...

                                                                           arg__from  \
block_number transaction_index log_index
10450640     159               153        0x0000000000000000000000000000000000000000
10450649     222               173        0x19f12c947d25ff8a3b748829d8001ca09a28d46d
                               176        0x0a0bbf3d159883bc7c9b6456d6888023a8265aad
10476280     131               164        0xb8541e73aa47a847fa39e803d19a3f9b1bbc5a6c
10476285     187               123        0xb8541e73aa47a847fa39e803d19a3f9b1bbc5a6c

                                                                             arg__to  \
block_number transaction_index log_index
10450640     159               153        0x19f12c947d25ff8a3b748829d8001ca09a28d46d
10450649     222               173        0x0a0bbf3d159883bc7c9b6456d6888023a8265aad
                               176        0xb8541e73aa47a847fa39e803d19a3f9b1bbc5a6c
10476280     131               164        0x4186c5aed424876f7ebe52f9148552a45e17f287
10476285     187               123        0xd8bae7d96df905e46718b6cee3410f535e11bf20

                                          arg__amount
block_number transaction_index log_index
10450640     159               153        100000000.0
10450649     222               173        100000000.0
                               176        100000000.0
10476280     131               164         60000000.0
10476285     187               123          5000000.0

In [9]:
df = pd.read_parquet("./data/stkmta_staked.parquet")
df.head()

,,,address,block_hash,transaction_hash,contract_address,event_name,event_hash,arg__user,arg__amount,arg__delegatee
block_number,transaction_index,log_index,,,,,,,,,
13236086,141,271,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,0xa84ab77ec59b5b46dbaff258e3ad01c3fcb60a4232be...,0xcf68f7a903ba479d8204e696fd021c925602e5523c40...,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,Staked,0x9f9e4044c5742cca66ca090b21552bac14645e68bad7...,0x19f12c947d25ff8a3b748829d8001ca09a28d46d,200000000000000000000,0x0000000000000000000000000000000000000000
13236789,29,73,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,0x33862e3beadce5ba537deb85a74827127203ce845405...,0x6b60abd1633e794511bf574fb7aad7031b92421f5d9e...,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,Staked,0x9f9e4044c5742cca66ca090b21552bac14645e68bad7...,0x19f12c947d25ff8a3b748829d8001ca09a28d46d,16043320105818350,0x0000000000000000000000000000000000000000
13238034,125,181,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,0x960b9c7a4789b435312299a61f031e8fe3c8cb57ad6a...,0x9cee7f22ad040680951dbabe78fca93e5daed8feccce...,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,Staked,0x9f9e4044c5742cca66ca090b21552bac14645e68bad7...,0x365a0a0492c5589ec4f04a9323f483d0de6e1df7,26828042192087496519597,0x0000000000000000000000000000000000000000
13238215,28,69,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,0x9088460f221044b3a346de0a00f24dfcad12c38f82c1...,0xf0fbc350b5c9c5e1b3c5defbf17e2746a02a98b72462...,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,Staked,0x9f9e4044c5742cca66ca090b21552bac14645e68bad7...,0x299a7db82536cd965424213f85ebbf0dbf4eda5f,271235249918347257302,0x365a0a0492c5589ec4f04a9323f483d0de6e1df7
13239687,243,431,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,0x3720b94a29ae1b84e15dbd3084058257d5ba77e48866...,0x96f7a29a01c7fb1e66acf763bef33fd970236d3cde06...,0x8f2326316ec696f6d023e37a9931c2b2c177a3d7,Staked,0x9f9e4044c5742cca66ca090b21552bac14645e68bad7...,0xf7749b41db006860cec0650d18b8013d69c44eeb,1803757722198788025856,0x0000000000000000000000000000000000000000